# Пользователи
## Создать нового пользователя

POST http://localhost:5001/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "wendy@example.com",
  "avatarPath": "wendy.jpg",
  "firstname": "Wendy",
  "lastname": "Torrance",
  "password": "Redrum2025!",
  "name": "WendyT",
  "type": "pro"
}


###

## Авторизовать пользователя

POST http://localhost:5001/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "wendy@example.com",
  "password": "Redrum2025!"
}

###

## Отправить изображение
@file = C:/Users/Public/photo.jpg

POST http://localhost:5001/users/6844046b531f936e584b6e2b/avatar HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IndlbmR5QGV4YW1wbGUuY29tIiwibmFtZSI6IldlbmR5VCIsInR5cGUiOiJwcm8iLCJpZCI6IjY4NDQwNTdkNTMxZjkzNmU1ODRiNmUzMyIsImlhdCI6MTc0OTI4ODMzMSwiZXhwIjoxNzQ5NDYxMTMxfQ.RrjUcKoxuO48XQcDoFXV1Z0WzXhuLpa0E0BXtdRoo9s
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="wendy.jpg"
Content-Type: image/jpeg

< {{file}}
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Проверить токен пользователя
GET http://localhost:5001/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IndlbmR5QGV4YW1wbGUuY29tIiwibmFtZSI6IldlbmR5VCIsInR5cGUiOiJwcm8iLCJpZCI6IjY4NDQwNTdkNTMxZjkzNmU1ODRiNmUzMyIsImlhdCI6MTc0OTI4ODMzMSwiZXhwIjoxNzQ5NDYxMTMxfQ.RrjUcKoxuO48XQcDoFXV1Z0WzXhuLpa0E0BXtdRoo9s

###
