# Предложения
## Получить список предложений
GET http://localhost:5001/offers HTTP/1.1
Content-Type: application/json

###

# Получить объявление по идентификатору
GET http://localhost:5001/offers/68440c9f288f0449dcd8644c HTTP/1.1
Authorization: Bearer <token>

###

## Создать новое объявление

POST http://localhost:5001/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer <token>

{
  "title": "Современный лофт с видом на Эйфелеву башню",
  "description": "Просторный светлый лофт в центре Парижа, идеален для романтического отпуска.",
  "price": 2500,
  "town": "Paris",
  "previewImage": "eiffel-loft.jpg",
  "images": ["img1.jpg", "img2.jpg", "img3.jpg", "img4.jpg", "img5.jpg", "img6.jpg"],
  "isPremium": true,
  "type": "apartment",
  "bedrooms": 1,
  "maxAdults": 2,
  "amenities": ["Breakfast", "Air conditioning", "Washer", "Towels", "Fridge"],
  "userId": "67f4f3ae4d7b90c77bd3c3ed",
  "longitude": 5.5,
  "latitude": 45
}

###

## Удалить объявление по идентификатору

DELETE http://localhost:5001/offers/68440c9f288f0449dcd8644c HTTP/1.1
Authorization: Bearer <token>
###

## Обновить объявление

PATCH http://localhost:5001/offers/68440c9f288f0449dcd8644c HTTP/1.1
Content-Type: application/json
Authorization: Bearer <token>

{
  "title": "Просторная квартира рядом с центром города",
  "price": 1950,
  "amenities": ["Air conditioning", "Baby seat", "Dishwasher"]
}

###

## Список объявлений из определенного города

GET http://localhost:5001/offers/Paris/premium HTTP/1.1
Accept: application/json

###

## Список комментариев к объявлению
GET http://localhost:5001/offers/6844399e57bbd51fd9a4ace5/comments HTTP/1.1
Accept: application/json

###

## Добавить объявление в избранное

POST http://localhost:5001/offers/68440c9f288f0449dcd8644c/favorite HTTP/1.1
Content-Type: application/json
Authorization: Bearer <token>

###

## Удалить объявление из избранного

DELETE http://localhost:5001/offers/68440c9f288f0449dcd8644c/favorite HTTP/1.1
Content-Type: application/json
Authorization: Bearer <token>

###

## Получить избранные объявления пользователя

GET http://localhost:5001/offers/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer <token>
