# Комментарии
## Создать комментарий

POST http://localhost:5001/comments/6844399e57bbd51fd9a4ace5
Content-Type: application/json
Authorization: Bearer <token>

{
  "text": "Всё было прекрасно",
  "rate": 5
}

###

